spring.application.name=restclient.pve
jwt.secret=90728052-4af7-4df6-84a8-eebece222a6f
proxmox.api.token=PVEAPIToken=spring-api@pve!backend=5348988c-4db6-46ec-a0a1-cb713f06f822
proxmox.api.url=https://10.10.1.11:8006/api2/json
proxmox.timeout.connect=10
proxmox.timeout.read=15